version: '3.8'

services:
  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    container_name: node-api
    tty: true
    restart: always
    volumes:
      - ./node-api:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
